window.COSMOS_QUIZ_I18N=window.COSMOS_QUIZ_I18N||{};window.COSMOS_QUIZ_I18N.es=[
['¿Qué planeta tiene más lunas conocidas?',['Júpiter','Saturno','Urano','Neptuno'],'Saturno tiene 146 lunas conocidas, más que cualquier otro planeta.'],
['¿Cuánto tarda la luz del Sol en llegar a la Tierra?',['8 segundos','8 minutos','8 horas','8 días'],'La luz del Sol tarda unos 8 minutos y 20 segundos en llegar a la Tierra.'],
['¿Cuál es el planeta más caliente?',['Mercurio','Venus','Marte','Júpiter'],'La densa atmósfera de CO₂ de Venus atrapa el calor, alcanzando unos 465 °C.'],
['¿Cuál es el volcán más alto del Sistema Solar?',['Mauna Kea','Monte Everest','Olympus Mons','Maxwell Montes'],'Olympus Mons, en Marte, se eleva unos 22 km.'],
['¿Qué planeta gira de lado?',['Neptuno','Urano','Saturno','Venus'],'Urano está inclinado unos 98°, probablemente por una colisión antigua.'],
['¿Cuándo se reclasificó a Plutón como planeta enano?',['1996','2001','2006','2015'],'La UAI reclasificó a Plutón en 2006.'],
['¿Qué luna tiene lagos de metano líquido?',['Europa','Ío','Titán','Ganímedes'],'Titán tiene lagos y mares de metano y etano.'],
['¿Cuál es la luna más grande del Sistema Solar?',['Titán','Ganímedes','La Luna','Calisto'],'Ganímedes es más grande que el planeta Mercurio.'],
['¿Qué luna es el cuerpo volcánicamente más activo conocido?',['Ío','Encélado','Tritón','Europa'],'Ío tiene unos 400 volcanes activos, impulsados por las mareas de Júpiter.'],
['¿Qué edad tiene el universo?',['4.600 millones de años','10.000 millones de años','13.800 millones de años','100.000 millones de años'],'El Big Bang ocurrió hace unos 13.800 millones de años.'],
['¿Qué porcentaje de toda la materia es materia oscura?',['15 %','50 %','85 %','99 %'],'Cerca del 85 % de toda la materia es materia oscura invisible.'],
['¿Cuál es la estrella más cercana al Sol?',['Sirio','Próxima Centauri','Betelgeuse','Vega'],'Próxima Centauri está a 4,24 años luz.'],
['¿Cuál es la estrella más brillante del cielo nocturno?',['Polaris','Betelgeuse','Sirio','Rigel'],'Sirio, la Estrella Perro, es la más brillante de la noche.'],
['¿En qué constelación está Betelgeuse?',['Orión','Tauro','Lira','Cisne'],'Betelgeuse marca el hombro de Orión.'],
['¿Cuánto mide aproximadamente una estrella de neutrones?',['20 km','2.000 km','20.000 km','Como el Sol'],'Una estrella de neutrones concentra más masa que el Sol en unos 20 km.'],
['¿Qué gran galaxia espiral chocará con la Vía Láctea?',['Sombrero','Remolino','Andrómeda','Molinete'],'Andrómeda se fusionará con la Vía Láctea en unos 4.500 millones de años.'],
['¿Qué hay en el centro de la Vía Láctea?',['Una estrella de neutrones','Un agujero negro supermasivo','Una gigante roja','Espacio vacío'],'Sagitario A* tiene unas 4 millones de veces la masa del Sol.'],
['¿En qué nebulosa están los Pilares de la Creación?',['Nebulosa de Orión','Nebulosa del Águila','Nebulosa del Cangrejo','Nebulosa del Anillo'],'Los Pilares están dentro de la Nebulosa del Águila (M16).'],
['¿En qué año se vio la supernova de la Nebulosa del Cangrejo?',['1054','1572','1604','1987'],'Astrónomos chinos la registraron en 1054 d.C.'],
['¿De qué se forma una nebulosa planetaria?',['Un planeta en formación','Una estrella moribunda tipo Sol','Dos planetas al chocar','La cola de un cometa'],'Es gas expulsado por una estrella tipo Sol al final de su vida.'],
['¿Cuándo se publicó la primera imagen de un agujero negro?',['1999','2009','2019','2023'],'El Telescopio del Horizonte de Sucesos fotografió M87* en 2019.'],
['¿Qué gas causa la mayor parte del verde en las auroras?',['Nitrógeno','Oxígeno','Helio','Hidrógeno'],'El oxígeno a 100–300 km de altitud brilla en verde.'],
['¿Hacia dónde apunta la cola de un cometa?',['Hacia el Sol','En dirección opuesta al Sol','Siempre detrás','Hacia la Tierra'],'El viento solar empuja la cola en dirección opuesta al Sol.'],
['¿Cuál es el mayor objeto del cinturón de asteroides?',['Vesta','Ceres','Pallas','Psyche'],'Ceres mide unos 940 km y cuenta como planeta enano.'],
['¿Qué causa las lluvias de meteoros?',['Fulguraciones solares','Restos de cometas','Polvo lunar','Satélites rotos'],'La Tierra atraviesa estelas de polvo dejadas por cometas.'],
['¿Desde cuándo está la ISS habitada sin interrupción?',['1990','1998','2000','2011'],'Está habitada de forma continua desde noviembre de 2000.'],
['¿Cuántos amaneceres ven al día los astronautas de la ISS?',['1','4','16','50'],'La ISS orbita la Tierra unas 16 veces al día.'],
['¿Qué telescopio se lanzó el día de Navidad de 2021?',['Hubble','Kepler','James Webb','Spitzer'],'Webb se lanzó el 25 de diciembre de 2021.'],
['¿Qué tipo de luz observa principalmente Webb?',['Rayos X','Ultravioleta','Infrarroja','Radio'],'La luz infrarroja permite a Webb ver a través del polvo y hasta el universo primitivo.'],
['¿Cuál es el objeto humano más lejano?',['Voyager 1','Voyager 2','New Horizons','Pioneer 10'],'La Voyager 1 está a más de 165 UA del Sol.'],
['¿Quién fue la primera persona en caminar sobre la Luna?',['Buzz Aldrin','Yuri Gagarin','Neil Armstrong','Michael Collins'],'Neil Armstrong pisó la Luna el 20 de julio de 1969.'],
['¿Qué róver llevó el helicóptero Ingenuity a Marte?',['Curiosity','Perseverance','Opportunity','Zhurong'],'Ingenuity viajó con Perseverance e hizo 72 vuelos.'],
['En la mitología griega, ¿de quién es gemela Artemisa?',['Zeus','Apolo','Hermes','Atenea'],'Artemisa es la hermana gemela de Apolo.'],
['¿Qué temperatura tiene el fondo cósmico de microondas?',['0 K','2,7 K','27 K','273 K'],'El CMB está a unos 2,725 kelvin.'],
['¿Qué hace la energía oscura?',['Mantiene unidas las galaxias','Acelera la expansión cósmica','Alimenta las estrellas','Crea agujeros negros'],'La energía oscura hace que el universo se expanda cada vez más rápido.'],
['¿Cómo se descubren la mayoría de exoplanetas?',['Fotos directas','Caídas de brillo estelar','Señales de radio','Sondas espaciales'],'La mayoría se hallan por la pequeña caída de luz cuando un planeta pasa por delante de su estrella.'],
['¿Qué luna lanza géiseres de agua desde su polo sur?',['Encélado','Titán','Calisto','Fobos'],'Cassini halló chorros saliendo de las “rayas de tigre” de Encélado.'],
['¿Qué luna podría ocultar un océano con el doble de volumen que el de la Tierra?',['Europa','Ío','La Luna','Titán'],'El océano oculto de Europa podría tener el doble de agua que los océanos terrestres.'],
['¿Cuánto dura un año en Mercurio?',['88 días','225 días','365 días','687 días'],'Mercurio orbita el Sol cada 88 días.'],
['¿Qué le da a Marte su color rojo?',['Plantas rojas','Polvo de óxido de hierro','Lava','Cobre'],'Un polvo de óxido de hierro parecido al óxido cubre la superficie de Marte.'],
['¿Qué planeta tiene el día más corto?',['La Tierra','Saturno','Júpiter','Mercurio'],'Júpiter gira una vez cada 9 h 56 min.'],
['¿Cómo se encontró Neptuno por primera vez?',['Con una sonda espacial','Por predicción matemática','En una foto accidental','Con un radiotelescopio'],'En 1846 se predijo su posición a partir de perturbaciones en la órbita de Urano.'],
['¿Cada cuánto vuelve aproximadamente el cometa Halley?',['Cada 7 años','Cada 76 años','Cada 200 años','Cada 1.000 años'],'Halley regresa cada 76 años aproximadamente; su próxima visita es en 2061.'],
['¿Por qué la Luna puede cubrir exactamente el Sol en un eclipse?',['La Luna es más grande','Coinciden las proporciones de tamaño y distancia','La sombra de la Tierra ayuda','Las nubes tapan el resto'],'El Sol es unas 400× más ancho pero también unas 400× más lejano.'],
['¿Qué causa una supernova de Tipo Ia?',['Una enana blanca que explota','Planetas que chocan','Agujeros negros que se fusionan','El impacto de un cometa'],'Una enana blanca que acumula demasiada materia puede explotar.'],
['¿Qué está haciendo la Luna poco a poco?',['Acercarse','Alejarse','Encogerse rápido','Girar más rápido'],'Se aleja de la Tierra unos 3,8 cm cada año.'],
['¿Qué galaxia fue la primera reconocida como espiral?',['Andrómeda','Remolino','Sombrero','Vía Láctea'],'Lord Rosse dibujó la espiral del Remolino en 1845.'],
['¿Qué forma el “ala” de la Galaxia del Sombrero?',['Un anillo de polvo','Un cinturón de cometas','Una segunda galaxia','Una nebulosa'],'Una banda oscura de polvo le da su forma de ala de sombrero.'],
['¿De dónde viene el campo magnético de la Tierra?',['La Luna','Hierro fundido en el núcleo externo','Los océanos','La atmósfera'],'El hierro líquido en movimiento del núcleo externo crea el campo magnético.'],
['¿Cuántos planetas hay en nuestro Sistema Solar?',['7','8','9','10'],'Hay ocho planetas, de Mercurio a Neptuno.'],
['¿Qué planeta se conoce como el Planeta Rojo?',['Venus','Marte','Júpiter','Mercurio'],'Marte se ve rojo por el polvo de óxido de hierro.'],
['¿Cuál es el planeta más grande?',['Saturno','Neptuno','Júpiter','La Tierra'],'Júpiter tiene más del doble de masa que todos los demás planetas juntos.'],
['¿Qué es el Sol?',['Un planeta','Una estrella','Un cometa','Una galaxia'],'El Sol es una estrella de secuencia principal de tipo G.'],
['¿Qué planeta es famoso por sus brillantes anillos?',['Marte','Saturno','Venus','Mercurio'],'Los anillos de Saturno están hechos de hielo y roca.'],
['¿Cómo se llama nuestra galaxia?',['Andrómeda','Vía Láctea','Sombrero','Remolino'],'Vivimos en la Vía Láctea.'],
['¿Qué planeta está más cerca del Sol?',['Venus','La Tierra','Mercurio','Marte'],'Mercurio orbita a 0,39 UA del Sol.'],
['¿Dónde viven hoy los astronautas en órbita?',['Una base lunar','La ISS','Skylab','Mir'],'Se vive de forma continua en la ISS desde el año 2000.'],
['¿Qué telescopio espacial se lanzó en 1990?',['Webb','Hubble','Kepler','Chandra'],'Hubble se lanzó en abril de 1990.'],
['¿Qué causa las auroras?',['La luz de la Luna','Partículas cargadas del Sol','Volcanes','Rayos'],'Partículas del viento solar chocan con gases de la atmósfera superior y las hacen brillar.'],
['¿Qué planeta tiene una tormenta hexagonal en su polo norte?',['Júpiter','Saturno','Neptuno','Urano'],'El polo norte de Saturno tiene una corriente en chorro con forma de hexágono.'],
['¿Cómo se llaman las dos lunas de Marte?',['Ío y Europa','Fobos y Deimos','Titán y Rea','Tritón y Nereida'],'Fobos y Deimos significan “miedo” y “pánico”.'],
['¿Qué misión llevó por primera vez humanos a la Luna?',['Apolo 8','Apolo 11','Apolo 13','Gemini 4'],'El Apolo 11 aterrizó el 20 de julio de 1969.'],
['¿Quién descubrió el primer púlsar en 1967?',['Vera Rubin','Jocelyn Bell Burnell','Carl Sagan','Edwin Hubble'],'Jocelyn Bell Burnell lo detectó siendo estudiante de doctorado.'],
['¿Qué es Sputnik Planitia?',['Un cráter en Marte','El glaciar con forma de corazón de Plutón','Una sonda soviética','Un mar lunar'],'Es una vasta llanura de hielo de nitrógeno en Plutón.'],
['¿Qué hizo la misión DART de la NASA en 2022?',['Aterrizó en Marte','Cambió la órbita de un asteroide','Tomó muestras de un cometa','Fotografió Plutón'],'DART impactó el asteroide Dimorphos y acortó su órbita.'],
['¿Cuántas personas han caminado sobre la Luna?',['6','12','18','24'],'Doce astronautas caminaron sobre la Luna en seis aterrizajes del Apolo.'],
['¿Qué alimenta el brillo de la Nebulosa del Cangrejo?',['Un agujero negro','Un púlsar','Una gigante roja','Un cometa'],'Un púlsar que gira 30 veces por segundo aporta la energía.'],
['¿Qué luna orbita su planeta al revés?',['Titán','Tritón','Europa','Fobos'],'Tritón, la luna de Neptuno, tiene una órbita retrógrada.']
];
